CC=gcc
CFLAGS=  -Wextra -Werror -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast  -Wreturn-type -std=c11
all: 
	$(CC) $(CFLAGS) 3*_extcopy.c -o extcopy