CC=gcc
CFLAGS= -Wall -Wextra -Werror -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast  -Wreturn-type 
all: 
	$(CC) $(CFLAGS) 2.2_dprintf.c -o dprintf