CC=gcc
CFLAGS= -Wall -Wextra -Werror -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast  -Wreturn-type -std=c11
all: 
	$(CC) $(CFLAGS) 3.2_pcopy.c -o pcopy